# GitHub Sponsors funding options
github: sergiohromano# Add your GitHub username here when you set up GitHub Sponsors

# Other funding platforms
patreon: # Add your Patreon username
open_collective: # Add your Open Collective username
ko_fi: # Add your Ko-fi username
tidelift: # Add your Tidelift package name
community_bridge: # Add your Community Bridge project name
liberapay: # Add your Liberapay username
issuehunt: # Add your IssueHunt username
otechie: # Add your Otechie username
lfx_crowdfunding: # Add your LFX Crowdfunding project name

# Custom funding URLs
custom: # Add custom funding URLs
  - https://cafecito.app/sergiohromano
  # - https://paypal.me/username
  # - https://buy-me-a-coffee.com/username 